-- promoter_partners table schema
CREATE TABLE IF NOT EXISTS promoter_partners (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trn TEXT REFERENCES business_details(trn) ON DELETE CASCADE,
    first_name TEXT,
    middle_name TEXT,
    last_name TEXT,
    father_first_name TEXT,
    father_middle_name TEXT,
    father_last_name TEXT,
    dob DATE,
    mobile TEXT,
    email TEXT,
    gender TEXT,
    std_code TEXT,
    telephone TEXT,
    designation TEXT,
    din TEXT,
    citizen_of_india BOOLEAN DEFAULT true,
    pan TEXT,
    passport TEXT,
    aadhaar TEXT,
    country TEXT DEFAULT 'India',
    pin_code TEXT,
    state TEXT,
    district TEXT,
    city TEXT,
    locality TEXT,
    road TEXT,
    premises TEXT,
    building_no TEXT,
    floor_no TEXT,
    landmark TEXT,
    also_signatory BOOLEAN DEFAULT false,
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(trn)
);

ALTER TABLE promoter_partners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions" ON promoter_partners FOR ALL USING (true);
